cwagnerFinancialPortal/Models/Budget/BudgetDetailsViewModel.cs
using cwagnerFinancialPortal.Domain.Budgets;
using System.Collections.Generic;

namespace cwagnerFinancialPortal.Models.Budget
{
    public class BudgetDetailsViewModel
    {
        public int Id { get; set; }
        public decimal Total { get; set; }
        public Duration Duration { get; set; }

        public List<BudgetItemViewModel> BudgetItems { get; set; }
    }
}

cwagnerFinancialPortal/Models/Budget/BudgetIndexViewModel.cs
using cwagnerFinancialPortal.Models.Category;
using System.Collections.Generic;

namespace cwagnerFinancialPortal.Models.Budget
{
    public class BudgetIndexViewModel
    {
        public List<BudgetViewModel> Budgets { get; set; }
        public List<CategoryViewModel> Categories { get; set; }
    }
}

cwagnerFinancialPortal/Models/Budget/BudgetItemViewModel.cs
namespace cwagnerFinancialPortal.Models.Budget
{
    public class BudgetItemViewModel
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
    }
}

cwagnerFinancialPortal/Models/Budget/BudgetViewModel.cs
using cwagnerFinancialPortal.Domain.Budgets;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace cwagnerFinancialPortal.Models.Budget
{
    public class BudgetViewModel
    {
        public int Id { get; set; }
        public decimal Total { get; set; }
        public Duration Duration { get; set; }
    }
}

cwagnerFinancialPortal/Models/Budget/CreateBudgetItemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace cwagnerFinancialPortal.Models.Budget
{
    public class CreateBudgetItemViewModel
    {
        public int BudgetId { get; set; }
        public decimal Amount { get; set; }
        public int CategoryId { get; set; }

        public SelectList CategorySelectList { get; set; }
    }
}

cwagnerFinancialPortal/Models/Budget/CreateBudgetViewModel.cs
using cwagnerFinancialPortal.Domain.Budgets;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace cwagnerFinancialPortal.Models.Budget
{
    public class CreateBudgetViewModel
    {
        public Duration Duration { get; set; }
    }
}

cwagnerFinancialPortal/Models/Budget/DeleteBudgetItemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace cwagnerFinancialPortal.Models.Budget
{
    public class DeleteBudgetItemViewModel
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
    }
}

cwagnerFinancialPortal/Models/Budget/DeleteBudgetViewModel.cs
using cwagnerFinancialPortal.Domain.Budgets;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace cwagnerFinancialPortal.Models.Budget
{
    public class DeleteBudgetViewModel
    {
        public int Id { get; set; }
        public decimal Total { get; set; }
        public Duration Duration { get; set; }
    }
}

cwagnerFinancialPortal/Models/Budget/EditBudgetItemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace cwagnerFinancialPortal.Models.Budget
{
    public class EditBudgetItemViewModel
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public int CategoryId { get; set; }

        public SelectList CategorySelectList { get; set; }
    }
}

cwagnerFinancialPortal/Models/Budget/EditBudgetViewModel.cs
using cwagnerFinancialPortal.Domain.Budgets;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace cwagnerFinancialPortal.Models.Budget
{
    public class EditBudgetViewModel
    {
        public int Id { get; set; }
        public Duration Duration { get; set; }
    }
}

cwagnerFinancialPortal/Controllers/BudgetController.cs
using cwagnerFinancialPortal.Domain;
using cwagnerFinancialPortal.Domain.Budgets;
using cwagnerFinancialPortal.Domain.Categories;
using cwagnerFinancialPortal.Extensions;
using cwagnerFinancialPortal.Models.Budget;
using cwagnerFinancialPortal.Models.Category;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace cwagnerFinancialPortal.Controllers
{
    [Authorize]
    [RequireHttps]
    public class BudgetController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly BudgetManager _budgetManager;
        private readonly CategoryManager _categoryManager;

        public BudgetController()
        {
            _db = new ApplicationDbContext();
            _budgetManager = new BudgetManager(_db);
            _categoryManager = new CategoryManager(_db);
        }

        //================
        //-----BUDGET-----
        //================

        // GET: Budget
        public ActionResult Index()
        {
            var householdId = User.Identity.GetHouseholdId();
            var model = new BudgetIndexViewModel();

            if (householdId != null)
            {
                model.Budgets = _budgetManager.GetAll(householdId.Value).Select(b => new BudgetViewModel
                {
                    Id = b.Id,
                    Duration = b.Duration,
                    Total = b.BudgetItems.Select(s =>s.Amount).DefaultIfEmpty().Sum(),
                    BudgetItems = b.BudgetItems.Select(bi => new BudgetItemViewModel
                    {
                        Id = bi.Id,
                        Amount = bi.Amount,
                        CategoryId = bi.CategoryId,
                        CategoryName = bi.Category.Name
                    }).ToList()
                }).ToList();
                model.Categories = _categoryManager.GetAll(householdId.Value).Select(c => new CategoryViewModel { Id = c.Id, Name = c.Name, CanEdit = c.HouseholdId.HasValue }).ToList();
            }
            return View(model);
        }

        //POST: Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateBudgetViewModel model)
        {
            var householdId = User.Identity.GetHouseholdId();
            if (ModelState.IsValid && householdId != null)
            {
                _budgetManager.Add(new Budget { HouseholdId = householdId.Value, Duration = model.Duration });
            }
            return RedirectToAction(nameof(Index));
        }

        public PartialViewResult CreateBudgetModal()
        {
            return PartialView();
        }

        //GET: Details
        [HttpGet]
        public ActionResult Details(int id)
        {
            var model = new BudgetDetailsViewModel();
            var householdId = User.Identity.GetHouseholdId();
            var budget = _budgetManager.Get(id, householdId.Value);
            model.Id = budget.Id;
            model.Total = budget.Total;
            model.Duration = budget.Duration;
            model.BudgetItems = budget.BudgetItems.ToList().Select(i => new BudgetItemViewModel
            {
                Id = i.Id,
                Amount = i.Amount,
                CategoryId = i.CategoryId
            }).ToList();
            return View(model);
        }

        //POST: Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditBudgetViewModel model)
        {
            if (ModelState.IsValid)
            {
                var householdId = User.Identity.GetHouseholdId();
                var budget = _budgetManager.Get(model.Id, householdId.Value);
                budget.Duration = model.Duration;
                _budgetManager.Edit(budget);
            }
            return RedirectToAction("Index");
        }

        public PartialViewResult EditBudgetModal(int id)
        {
            var householdId = User.Identity.GetHouseholdId();
            var budget = _budgetManager.Get(id, householdId.Value);
            var model = new EditBudgetViewModel()
            {
                Duration = budget.Duration,
            };
            return PartialView(model);
        }

        //POST: Delete
        [HttpPost]
        public ActionResult Delete(int id)
        {
            _budgetManager.Delete(id);
            return RedirectToAction("Index");
        }

        public PartialViewResult DeleteBudgetModal(int id)
        {
            var householdId = User.Identity.GetHouseholdId();
            var budget = _budgetManager.Get(id, householdId.Value);
            var model = new DeleteBudgetViewModel
            {
                Id = budget.Id,
                Duration = budget.Duration,
                Total = budget.BudgetItems.Select(s => s.Amount).DefaultIfEmpty().Sum()
            };
            return PartialView(model);
        }

        //======================
        //-----BUDGET-ITEMS-----
        //======================

        public PartialViewResult BudgetItemListPartial(IEnumerable<BudgetItemViewModel> model)
        {
            return PartialView(model);
        }

        //POST: Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateItem(CreateBudgetItemViewModel model)
        {
            var householdId = User.Identity.GetHouseholdId();
            if (ModelState.IsValid && householdId != null)
            {
                _budgetManager.AddItem(new BudgetItem { BudgetId = model.BudgetId, Amount = model.Amount, CategoryId = model.CategoryId });
            }
            return RedirectToAction("Index");
        }

        [Route("Budget/CreateBudgetItemModal/{budgetId:int}")]
        public PartialViewResult CreateBudgetItemModal(int budgetId)
        {
            var categories = _categoryManager.GetAll(User.Identity.GetHouseholdId().Value);
            var model = new CreateBudgetItemViewModel
            {
                BudgetId = budgetId,
                CategorySelectList = new SelectList(categories, "Id", "Name")
            };

            return PartialView(model);
        }

        //POST: Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditItem(EditBudgetItemViewModel model)
        {
            if (ModelState.IsValid)
            {
                var budgetItem = _budgetManager.GetItem(model.Id);
                budgetItem.Amount = model.Amount;
                budgetItem.CategoryId = model.CategoryId;
                _budgetManager.EditItem(budgetItem);
            }
            return RedirectToAction("Index");
        }

        public PartialViewResult EditBudgetItemModal(int id)
        {
            var budgetItem = _budgetManager.GetItem(id);
            var categories = _categoryManager.GetAll(User.Identity.GetHouseholdId().Value);
            var model = new EditBudgetItemViewModel()
            {
                Amount = budgetItem.Amount,
                CategoryId = budgetItem.CategoryId,
                CategorySelectList = new SelectList(categories, "Id", "Name", budgetItem.CategoryId)
            };
            return PartialView(model);
        }

        //POST: Delete
        [HttpPost]
        public ActionResult DeleteItem(int id)
        {
            _budgetManager.DeleteItem(id);
            return RedirectToAction("Index");
        }

        public PartialViewResult DeleteBudgetItemModal(int id)
        {
            var budgetItem = _budgetManager.GetItem(id);
            var model = new DeleteBudgetItemViewModel
            {
                Id = budgetItem.Id,
                Amount = budgetItem.Amount,
                CategoryId = budgetItem.CategoryId
            };
            return PartialView(model);
        }

        //====================
        //-----CATEGORIES-----
        //====================

        public PartialViewResult CategoryListPartial(IEnumerable<CategoryViewModel> model)
        {
            return PartialView(model);
        }

        // POST: CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCategory(CreateCategoryViewModel model)
        {
            var householdId = User.Identity.GetHouseholdId();
            if (ModelState.IsValid && householdId != null)
            {
                _categoryManager.Add(new Category { HouseholdId = householdId.Value, Name = model.Name });
            }
            return RedirectToAction(nameof(Index));
        }

        public PartialViewResult CreateCategoryModal()
        {
            return PartialView();
        }

        //POST: EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCategory(EditCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                var householdId = User.Identity.GetHouseholdId();
                var category = _categoryManager.Get(model.Id, householdId.Value);
                category.Name = model.Name;
                _categoryManager.Edit(category);
            }
            return RedirectToAction("Index");
        }

        public PartialViewResult EditCategoryModal(int id)
        {
            var householdId = User.Identity.GetHouseholdId();
            var category = _categoryManager.Get(id, householdId.Value);
            var model = new EditCategoryViewModel()
            {
                Name = category.Name
            };
            return PartialView(model);
        }

        //POST: DELETE
        [HttpPost]
        public ActionResult DeleteCategory(int id)
        {
            _categoryManager.Delete(id);
            return RedirectToAction("Index");
        }

        public PartialViewResult DeleteCategoryModal(int id)
        {
            var householdId = User.Identity.GetHouseholdId();
            var category = _categoryManager.Get(id, householdId.Value);
            var model = new DeleteCategoryViewModel
            {
                Id = category.Id,

cwagnerFinancialPortal/Views/Budget/BudgetItemListPartial.cshtml
@model IEnumerable<cwagnerFinancialPortal.Models.Budget.BudgetItemViewModel>

<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    Amount
                </th>
                <th>
                    Category
                </th>
                <th>
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CategoryName)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "EditBudgetItemModal", new { id = item.Id }, new { data_target = "#modal", data_toggle = "modal", data_remote = "true" }) |
                        @Html.ActionLink("Delete", "DeleteBudgetItemModal", new { id = item.Id }, new { data_target = "#modal", data_toggle = "modal", data_remote = "true" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

cwagnerFinancialPortal/Views/Budget/CategoryListPartial.cshtml
@model IEnumerable<cwagnerFinancialPortal.Models.Category.CategoryViewModel>

<div class="table-responsive">
    <table class="table table-hover">
        <thead></thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @if (item.CanEdit)
                        {
                            @Html.ActionLink("Edit", "EditCategoryModal", new { id = item.Id }, new { data_target = "#modal", data_toggle = "modal", data_remote = "true" })
                            <span> | </span>
                            @Html.ActionLink("Delete", "DeleteCategoryModal", new { id = item.Id }, new { data_target = "#modal", data_toggle = "modal", data_remote = "true" })
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

cwagnerFinancialPortal/Views/Budget/CreateBudgetItemModal.cshtml
@model cwagnerFinancialPortal.Models.Budget.CreateBudgetItemViewModel

@using (Html.BeginForm("CreateItem", "Budget", FormMethod.Post, new { @class = "form-material form-horizontal" }))
{
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Add a budget item</h4>
    </div>
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => Model.BudgetId)
        <div class="form-group">
            <input class="form-control" type="text" name="@nameof(Model.Amount)" required="" placeholder="Amount">
        </div>
        <div class="form-group">
            <label for="budgetItem-category" class="control-label">Category:</label>
            @Html.DropDownListFor(model => model.CategoryId, Model.CategorySelectList)
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger waves-effect waves-light">Submit</button>
    </div>
}

cwagnerFinancialPortal/Views/Budget/CreateBudgetModal.cshtml
@model cwagnerFinancialPortal.Models.Budget.CreateBudgetViewModel

@using (Html.BeginForm("Create", "Budget", FormMethod.Post, new { @class = "form-material form-horizontal" }))
{
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Add a budget</h4>
    </div>
    <div class="modal-body">
        @Html.AntiForgeryToken()
        <div class="form-group">
            <label for="budget-name" class="control-label">Budget Duration: </label>
            @Html.EnumDropDownListFor(e => Model.Duration)
        </div>
        <div class="form-group">
            <p>Your budget total will be automatically calculated once items have been created.</p>
            <p>Click on the newly created budget to add budget categories and amounts.</p>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger waves-effect waves-light">Submit</button>
    </div>
}

cwagnerFinancialPortal/Views/Budget/CreateCategoryModal.cshtml
@model cwagnerFinancialPortal.Models.Category.CreateCategoryViewModel


@using (Html.BeginForm("CreateCategory", "Budget", FormMethod.Post, new { @class = "form-material form-horizontal" }))
{
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Add a category</h4>
    </div>
    <div class="modal-body">
        @Html.AntiForgeryToken()
        <div class="form-group">
            <input class="form-control" type="text" name="@nameof(Model.Name)" required="" placeholder="Category Name">
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger waves-effect waves-light">Submit</button>
    </div>
}

cwagnerFinancialPortal/Views/Budget/DeleteBudgetItemModal.cshtml
@model cwagnerFinancialPortal.Models.Budget.DeleteBudgetItemViewModel

<div class="modal-header">
    <h4 class="modal-title" id="myModalLabel"><b>WARNING!</b></h4>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
</div>
<div class="modal-body">
    <h4>Are you sure you want to delete the @Model.CategoryName category for @Model.Amount?</h4>
    <p>Your budget total will be automatically adjusted.</p>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancel</button>
    @using (Html.BeginForm("DeleteItem", "Budget", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(h => Model.Id)
        <button type="submit" class="btn btn-danger waves-effect waves-light">Delete</button>
    }
</div>

cwagnerFinancialPortal/Views/Budget/DeleteBudgetModal.cshtml
@model cwagnerFinancialPortal.Models.Budget.DeleteBudgetViewModel

<div class="modal-header">
    <h4 class="modal-title" id="myModalLabel"><b>WARNING!</b></h4>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
</div>
<div class="modal-body">
    <h4>Are you sure you want to delete the @Model.Duration budget for @Model.Total?</h4>
    <p>This budget and all of its items will be permanently deleted.</p>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancel</button>
    @using (Html.BeginForm("Delete", "Budget", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(h => Model.Id)
        <button type="submit" class="btn btn-danger waves-effect waves-light">Delete</button>
    }
</div>

cwagnerFinancialPortal/Views/Budget/DeleteCategoryModal.cshtml
@model cwagnerFinancialPortal.Models.Category.DeleteCategoryViewModel

<div class="modal-header">
    <h4 class="modal-title" id="myModalLabel"><b>WARNING!</b></h4>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
</div>
<div class="modal-body">
    <h4>Are you sure you want to delete the category, @Model.Name?</h4>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancel</button>
    @using (Html.BeginForm("DeleteCategory", "Budget", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(h => Model.Id)
        <button type="submit" class="btn btn-danger waves-effect waves-light">Delete</button>
    }
</div>

cwagnerFinancialPortal/Views/Budget/EditBudgetItemModal.cshtml
@model cwagnerFinancialPortal.Models.Budget.EditBudgetItemViewModel

@using (Html.BeginForm("EditItem", "Budget", FormMethod.Post, new { @class = "form-material form-horizontal" }))
{
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Edit this budget item</h4>
    </div>
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(e => Model.Id)
        <div class="form-group">
            <input class="form-control" type="text" name="@nameof(Model.Amount)" required="" value="@Model.Amount">
        </div>
        <div class="form-group">
            <label for="budgetItem-category" class="control-label">Category: </label>
            @Html.DropDownListFor(model => model.CategoryId, Model.CategorySelectList)
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger waves-effect waves-light">Save changes</button>
    </div>
}

cwagnerFinancialPortal/Views/Budget/EditBudgetModal.cshtml
@model cwagnerFinancialPortal.Models.Budget.EditBudgetViewModel

@using (Html.BeginForm("Edit", "Budget", FormMethod.Post, new { @class = "form-material form-horizontal" }))
{
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Edit this budget</h4>
    </div>
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(e => Model.Id)
        <div class="form-group">
            <label for="budget-name" class="control-label">Budget Duration: </label>
            @Html.EnumDropDownListFor(e => Model.Duration)
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger waves-effect waves-light">Save changes</button>
    </div>
}

cwagnerFinancialPortal/Views/Budget/EditCategoryModal.cshtml
@model cwagnerFinancialPortal.Models.Category.EditCategoryViewModel

@using (Html.BeginForm("EditCategory", "Budget", FormMethod.Post, new { @class = "form-material form-horizontal" }))
{
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Edit this category</h4>
    </div>
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(e => Model.Id)
        <div class="form-group">
            <input class="form-control" type="text" name="@nameof(Model.Name)" required="" value="@Model.Name">
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger waves-effect waves-light">Save changes</button>
    </div>
}

cwagnerFinancialPortal/Views/Budget/Index.cshtml
@model cwagnerFinancialPortal.Models.Budget.BudgetIndexViewModel
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Budgets</h4>
                        <h6 class="card-subtitle">@Html.ActionLink("Add Budget", "CreateBudgetModal", null, new { data_target = "#modal", data_toggle = "modal", data_remote = "true" })</h6>
                    </div>
                </div>
            </div>
        </div>
        @foreach (var item in Model.Budgets)
        {
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">
                        @Html.DisplayFor(m => item.Total)
                        @Html.DisplayFor(m => item.Duration)
                    </h4>
                    <h6 class="card-subtitle">
                        @Html.ActionLink("Edit", "EditBudgetModal", new { id = item.Id }, new { data_target = "#modal", data_toggle = "modal", data_remote = "true" }) |
                        @Html.ActionLink("Delete", "DeleteBudgetModal", new { id = item.Id }, new { data_target = "#modal", data_toggle = "modal", data_remote = "true" }) |
                        @Html.ActionLink("Add Budget Item", "CreateBudgetItemModal", new { budgetId = item.Id }, new { data_target = "#modal", data_toggle = "modal", data_remote = "true" })
                    </h6>
                    @Html.Action("BudgetItemListPartial", new { Model = item.BudgetItems })
                </div>`
            </div>
        }
    </div>
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Budget Categories</h4>
                <h6 class="card-subtitle">@Html.ActionLink("Add Category", "CreateCategoryModal", null, new { data_target = "#modal", data_toggle = "modal", data_remote = "true" })</h6>
                @Html.Action("CategoryListPartial", new { model = Model.Categories })
            </div>
        </div>
    </div>
</div>