cwagnerFinancialPortal/Models/BankAccount/BankAccountDetailsViewModel.cs
using cwagnerFinancialPortal.Models.Transaction;
using System.Collections.Generic;

namespace cwagnerFinancialPortal.Models.BankAccount
{
    public class BankAccountDetailsViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Balance { get; set; }

        public List<TransactionViewModel> Transactions { get; set; }
    }
}

cwagnerFinancialPortal/Models/BankAccount/BankAccountIndexViewModel.cs
using cwagnerFinancialPortal.Models.BankAccount;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace cwagnerFinancialPortal.Models
{
    public class BankAccountIndexViewModel
    {
        public List<BankAccountViewModel> Accounts { get; set; }
    }
}

cwagnerFinancialPortal/Models/BankAccount/BankAccountViewModel.cs
namespace cwagnerFinancialPortal.Models.BankAccount
{
    public class BankAccountViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Balance { get; set; }
    }
}

cwagnerFinancialPortal/Models/BankAccount/CreateBankAccountViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace cwagnerFinancialPortal.Models.BankAccount
{
    public class CreateBankAccountViewModel
    {
        public string Name { get; set; }
        public decimal Balance { get; set; }
    }
}

cwagnerFinancialPortal/Models/BankAccount/DeleteBankAccountViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace cwagnerFinancialPortal.Models.BankAccount
{
    public class DeleteBankAccountViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

cwagnerFinancialPortal/Models/BankAccount/EditBankAccountViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace cwagnerFinancialPortal.Models.BankAccount
{
    public class EditBankAccountViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

cwagnerFinancialPortal/Controllers/BankAccountController.cs
using System.Web.Mvc;
using cwagnerFinancialPortal.Domain.BankAccounts;
using cwagnerFinancialPortal.Extensions;
using cwagnerFinancialPortal.Models;
using cwagnerFinancialPortal.Models.BankAccount;
using System.Linq;
using cwagnerFinancialPortal.Domain.Transactions;
using cwagnerFinancialPortal.Models.Transaction;
using System.Collections.Generic;
using cwagnerFinancialPortal.Domain.Categories;
using cwagnerFinancialPortal.Domain;

namespace cwagnerFinancialPortal.Controllers
{
    [Authorize]
    [RequireHttps]
    public class BankAccountController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly CategoryManager _categoryManager;
        private readonly BankAccountManager _manager;

        public BankAccountController()
        {
            _db = new ApplicationDbContext();
            _categoryManager = new CategoryManager(_db);
            _manager = new BankAccountManager(_db);
        }

        // GET: BankAccount
        public ActionResult Index()
        {
            var householdId = User.Identity.GetHouseholdId();
            var model = new BankAccountIndexViewModel();

            if (householdId != null)
            {
                model.Accounts = _manager.GetAll(householdId.Value).Select(a => new BankAccountViewModel { Id = a.Id, Name = a.Name, Balance = a.Balance }).ToList();
            }
            return View(model);
        }

        //GET: BankAccount DETAILS
        public ActionResult Details(int id)
        {
            var model = new BankAccountDetailsViewModel();
            var account = _manager.Get(id);
            model.Id = account.Id;
            model.Name = account.Name;
            model.Balance = account.Balance;
            model.Transactions = account.Transactions.ToList().Select(t => new TransactionViewModel
            {
                Id = t.Id,
                Date = t.Date,
                Amount = t.Amount,
                Description = t.Description,
                CategoryName = t.Category.Name,
                CategoryId = t.CategoryId,
                Type = t.Type,
                IsReconciled = t.IsReconciled
            }).ToList();
            return View(model);
        }

        //POST: CREATE BankAccount
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateBankAccountViewModel model)
        {
            var householdId = User.Identity.GetHouseholdId();
            if (ModelState.IsValid && householdId != null)
            {
                _manager.Add(new BankAccount { HouseholdId = householdId.Value, Name = model.Name, Balance = model.Balance });
            }
            return RedirectToAction(nameof(Index));
        }

        public PartialViewResult CreateBankAccountModal()
        {
            return PartialView();
        }

        //POST: EDIT BankAccount
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditBankAccountViewModel model)
        {
            if (ModelState.IsValid)
            {
                var account = _manager.Get(model.Id);
                account.Name = model.Name;
                _manager.Edit(account);
            }
            return RedirectToAction("Index");
        }

        public PartialViewResult EditBankAccountModal(int id)
        {
            var account = _manager.Get(id);
            var model = new EditBankAccountViewModel()
            {
                Name = account.Name
            };
            return PartialView(model);
        }

        //POST: DELETE BankAccount
        [HttpPost]
        public ActionResult Delete(int id)
        {
            _manager.Delete(id);
            return RedirectToAction("Index");
        }

        public PartialViewResult DeleteBankAccountModal(int id)
        {
            var account = _manager.Get(id);
            var model = new DeleteBankAccountViewModel
            {
                Id = account.Id,
                Name = account.Name
            };
            return PartialView(model);
        }

        //======================
        //-----TRANSACTIONS-----
        //======================

        //POST: CREATE Transaction
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateTransaction(CreateTransactionViewModel model)
        {
            if (ModelState.IsValid)
            {
                _manager.AddTransaction(new Transaction
                {
                    BankAccountId = model.BankAccountId,
                    Date = model.Date,
                    Amount = model.Amount,
                    Description = model.Description,
                    Type = model.Type,
                    CategoryId = model.CategoryId,
                    IsReconciled = model.IsReconciled
                });
            }
            return RedirectToAction("Details", new { id = model.BankAccountId });
        }

        public PartialViewResult TransactionListPartial(IEnumerable<TransactionViewModel> model)
        {
            return PartialView(model);
        }

        public PartialViewResult CreateTransactionModal(int id)
        {
            var householdId = User.Identity.GetHouseholdId().Value;
            var availableCategories = _categoryManager.GetAll(householdId).ToList();
            var model = new CreateTransactionViewModel
            {
                BankAccountId = id,
                CategorySelectList = new SelectList(availableCategories, "Id", "Name")
            };
            return PartialView(model);
        }

        //POST: EDIT Transaction
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditTransaction(EditTransactionViewModel model)
        {
            var transaction = _manager.GetTransaction(model.Id);
            if (ModelState.IsValid)
            {
                transaction.Date = model.Date;
                transaction.Type = model.Type;
                transaction.Amount = model.Amount;
                transaction.Description = model.Description;
                transaction.CategoryId = model.CategoryId;
                transaction.IsReconciled = model.IsReconciled;
                _manager.EditTransaction(transaction);
            }
            return RedirectToAction("Details", new { id = transaction.BankAccountId });
        }

        public PartialViewResult EditTransactionModal(int id)
        {
            var householdId = User.Identity.GetHouseholdId().Value;
            var availableCategories = _categoryManager.GetAll(householdId).ToList();
            
            var transaction = _manager.GetTransaction(id);
            var model = new EditTransactionViewModel
            {
                Id = transaction.Id,
                Date = transaction.Date,
                Type = transaction.Type,
                Amount = transaction.Amount,
                Description = transaction.Description,
                CategoryId = transaction.CategoryId,
                IsReconciled = transaction.IsReconciled,
                CategorySelectList = new SelectList(availableCategories, "Id", "Name", transaction.CategoryId)
            };
            return PartialView(model);
        }

        //POST: DELETE Transaction
        [HttpPost]
        public ActionResult DeleteTransaction(int id)
        {
            var transaction = _manager.GetTransaction(id);
            _manager.DeleteTransaction(id);
            return RedirectToAction("Details", new { id = transaction.BankAccountId });
        }

        public PartialViewResult DeleteTransactionModal(int id)
        {
            var transaction = _manager.GetTransaction(id);
            var model = new DeleteTransactionViewModel
            {
                Id = transaction.Id,
                Description = transaction.Description,
                Amount = transaction.Amount
            };
            return PartialView(model);
        }
    }
}

cwagnerFinancialPortal/Views/BankAccount/CreateBankAccountModal.cshtml
@model cwagnerFinancialPortal.Models.BankAccount.CreateBankAccountViewModel
@{
    ViewBag.Title = "CreateBankAccountModalPartial";
}

@using (Html.BeginForm("Create", "BankAccount", FormMethod.Post, new { @class = "form-material form-horizontal" }))
{
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Add an account</h4>
    </div>
    <div class="modal-body">
        @Html.AntiForgeryToken()
        <div class="form-group">
            <input class="form-control" type="text" name="@nameof(Model.Name)" required="" placeholder="Account Name">
        </div>
        <div class="form-group">
            <input class="form-control" type="number" name="@nameof(Model.Balance)" required="" placeholder="Current Balance">
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger waves-effect waves-light">Submit</button>
    </div>
}

cwagnerFinancialPortal/Views/BankAccount/CreateTransactionModal.cshtml
@model cwagnerFinancialPortal.Models.Transaction.CreateTransactionViewModel
@{
    ViewBag.Title = "CreateTransactionModalPartialView";
}

@using (Html.BeginForm("CreateTransaction", "BankAccount", FormMethod.Post, new { @class = "form-material form-horizontal" }))
{
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Record a new transaction</h4>
    </div>
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(e => Model.BankAccountId)

        <div class="form-group">
            <input class="form-control" name="@nameof(Model.Date)" id="datepicker" type="text" placeholder="Date of transaction" required="">
        </div>
        <div class="form-group">
            <label for="message-text" class="control-label">Transaction type: </label>
            @Html.EnumDropDownListFor(model => model.Type)
        </div>
        <div class="form-group">
            <input class="form-control" name="@nameof(Model.Amount)" id="message-text" placeholder="Amount" required="">
        </div>
        <div class="form-group">
            <input class="form-control" name="@nameof(Model.Description)" id="message-text" placeholder="Description">
        </div>
        <div class="form-group">
            <label for="message-text" class="control-label">Category: </label>
            @Html.DropDownListFor(model => model.CategoryId, Model.CategorySelectList)
        </div>
        <div class="form-group">
            <div class="checkbox checkbox-success">
                <input id="IsReconciled" name="@nameof(Model.IsReconciled)" type="checkbox" value="true" @(Model?.IsReconciled == true ? "checked=\"checked\"" : "") />
                <label for="@nameof(Model.IsReconciled)" class="control-label">Has this been reconciled?</label>
            </div>
        </div>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger waves-effect waves-light">Save transaction</button>
    </div>
}

<script>
    $(function () {
        $("#datepicker").datepicker();
    });
</script>

cwagnerFinancialPortal/Views/BankAccount/DeleteBankAccountModal.cshtml
@model cwagnerFinancialPortal.Models.BankAccount.DeleteBankAccountViewModel

<div class="modal-header">
    <h4 class="modal-title" id="myModalLabel"><b>WARNING!</b></h4>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
</div>
<div class="modal-body">
    <h4>Are you sure you want to delete the bank account, @Model.Name?</h4>
    <p>This account and all of its transactions will be permanently deleted.</p>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancel</button>
    @using (Html.BeginForm("Delete", "BankAccount", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(h => Model.Id)
        <button type="submit" class="btn btn-danger waves-effect waves-light">Delete</button>
    }
</div>

cwagnerFinancialPortal/Views/BankAccount/DeleteTransactionModal.cshtml
@model cwagnerFinancialPortal.Models.Transaction.DeleteTransactionViewModel

<div class="modal-header">
    <h4 class="modal-title" id="myModalLabel"><b>WARNING!</b></h4>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
</div>
<div class="modal-body">
    <h4>Are you sure you want to void the transaction for the amount of @Model.Amount.ToString("C")?</h4>
    <p>This transaction will be removed from record and your balance adjusted.</p>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancel</button>
    @using (Html.BeginForm("DeleteTransaction", "BankAccount", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(h => Model.Id)
        <button type="submit" class="btn btn-danger waves-effect waves-light">Delete</button>
    }
</div>

cwagnerFinancialPortal/Views/BankAccount/Details.cshtml
@model cwagnerFinancialPortal.Models.BankAccount.BankAccountDetailsViewModel
@{
    ViewBag.Title = "Details";
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">@Model.Name</h4>
                <h6 class="card-subtitle">@Model.Balance</h6>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Transactions</h4>
                <h6 class="card-subtitle">@Html.ActionLink("Add Transaction", "CreateTransactionModal", new { id = Model.Id }, new { data_target = "#modal", data_toggle = "modal", data_remote = "true" })</h6>
                <div class="table-responsive m-t-40">
                    <table id="transactionTable" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                        @Html.Action("TransactionListPartial", new { Model = Model.Transactions })
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        $(document).ready(function () {
            $('#transactionTable').DataTable({
                responsive: true
            });
        });
    </script>
}

cwagnerFinancialPortal/Views/BankAccount/EditBankAccountModal.cshtml
@model cwagnerFinancialPortal.Models.BankAccount.EditBankAccountViewModel

@using (Html.BeginForm("Edit", "BankAccount", FormMethod.Post, new { @class = "form-material form-horizontal" }))
{
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Edit this account</h4>
    </div>
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(e => Model.Id)
        <div class="form-group">
            <input class="form-control" type="text" name="@nameof(Model.Name)" required="" value="@Model.Name">
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger waves-effect waves-light">Save changes</button>
    </div>
}

cwagnerFinancialPortal/Views/BankAccount/EditTransactionModal.cshtml
@model cwagnerFinancialPortal.Models.Transaction.EditTransactionViewModel

@using (Html.BeginForm("EditTransaction", "BankAccount", FormMethod.Post, new { @class = "form-material form-horizontal" }))
{
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Edit this transaction</h4>
    </div>
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(e => Model.Id)
        <div class="form-group">
            <input class="form-control" name="@nameof(Model.Date)" id="datepicker" type="text" value="@Model.Date.ToString("d")" required="">
        </div>
        <div class="form-group">
            <label for="message-text" class="control-label">Transaction type: </label>
            @Html.EnumDropDownListFor(model => model.Type)
        </div>
        <div class="form-group">
            <input class="form-control" type="text" name="@nameof(Model.Amount)" required="" value="@Model.Amount">
        </div>
        <div class="form-group">
            <input class="form-control" type="text" name="@nameof(Model.Description)" required="" value="@Model.Description">
        </div>
        <div class="form-group">
            <label for="message-text" class="control-label">Category: </label>
            @Html.DropDownListFor(model => model.CategoryId, Model.CategorySelectList)
        </div>
        <div class="form-group">
            <div class="checkbox checkbox-success">
                <input id="IsReconciled" name="@nameof(Model.IsReconciled)" type="checkbox" value="true" @(Model?.IsReconciled == true ? "checked=\"checked\"" : "") />
                <label for="@nameof(Model.IsReconciled)" class="control-label">Has this been reconciled?</label>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger waves-effect waves-light">Save transaction</button>
    </div>
}

<script>
    $(function () {
        $("#datepicker").datepicker();
    });
</script>

cwagnerFinancialPortal/Views/BankAccount/Index.cshtml
@model cwagnerFinancialPortal.Models.BankAccountIndexViewModel
@{
    ViewBag.Title = "Index";
}

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Bank Accounts</h4>
        <h6 class="card-subtitle">@Html.ActionLink("Add Account", "CreateBankAccountModal", null, new { data_target="#modal", data_toggle = "modal", data_remote = "true" })</h6>
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => Model.Accounts.First().Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => Model.Accounts.First().Balance)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Accounts)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Balance)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "EditBankAccountModal", new { id = item.Id}, new  { data_target = "#modal", data_toggle = "modal", data_remote = "true" }) |
                                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                @Html.ActionLink("Delete", "DeleteBankAccountModal", new { id = item.Id }, new { data_target = "#modal", data_toggle = "modal", data_remote = "true" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

cwagnerFinancialPortal/Views/BankAccount/TransactionListPartial.cshtml
@model IEnumerable<cwagnerFinancialPortal.Models.Transaction.TransactionViewModel>

@{
    ViewBag.Title = "TransactionPartialView";
}

<thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsReconciled)
        </th>
        <th>Actions</th>
    </tr>
</thead>
<tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Date.ToString("d")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsReconciledString)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditTransactionModal", new { id = item.Id }, new { data_target="#modal", data_toggle ="modal", data_remote = "true" }) |
                @Html.ActionLink("Void", "DeleteTransactionModal", new { id = item.Id }, new { data_target = "#modal", data_toggle = "modal", data_remote = "true" })
            </td>
        </tr>
    }
</tbody>